---

- hosts: all
  become: yes
  gather_facts: true
  ignore_errors: yes
  tasks:

    - name: print ipv4 
      debug:
        msg: "{{ansible_al_ipv4_addresses}}"
 
    - name: print ipv4 
      debug:
        msg: "{{ansible_os_famil}}"
   
    - name: print ipv4 
      debug:
        msg: "{{ansible_pkg_mgr}}"
