---

- hosts: ubuntu1
  become: yes
  tasks:
 
    - name: install packages
      apt:
        name: "{{item}}"
        state: present
      with_items:
          - apache2
          - python2.7
          - wget
          - tree
          - unzip 
