---

- hosts: centos1
  become: yes
  vars:
    tomcaturl: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.50/bin/apache-tomcat-8.5.50.tar.gz

  tasks:
  
    - name: create a file
      file:
        path: /home/ansadm/java.txt
        state: touch
        owner: root
        group: ansadm
        mode: 0666

    - name: download tomcat 8 version
      get_url:
        url: "{{tomcaturl}}"
        dest: /home/ansadm
      register: tomout

    - name: print tomcat download output
      debug:
        msg: "{{tomout}}"


    - name: untar tomcat 8 
      unarchive:
        src: "{{tomout.dest}}"
        dest: /home/ansadm
        remote_src: yes  

    - name: start tomcat
      shell: nohop /home/ansadm/apache-tomcat-8.5.50/bin/startup.sh &  
