---

- hosts: ubuntu1
  become: yes
  vars:
    os: REDHAT
  tasks:

#    - name: install httpd package
#      yum:
#        name: httpd
#        state: present

#    - name: start httpd service
#      service:
#        name: httpd
#        state: started
#        enabled: yes

    - name: copy index.html file
      template:
        src: template/index.j2 
        dest: /var/www/html/index.html
